version: '3'

services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: tail -f /dev/null
    network_mode: host
    cap_add:
      - sys_ptrace
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL:-4}
      - HOSTNAME=${TELE_SRV:-tele}.${DOMAIN:-docker.localhost}
      - PULSE_SERVER=unix:/run/pulse/socket
      - PULSE_COOKIE=/run/pulse/cookie
      - WEBSMSD_PORT=${WEBSMSD_PORT:-80}
    volumes:
      - asterisk-conf:/etc/asterisk
      - ./pulse:/run/pulse:rshared
      - /etc/localtime:/etc/localtime:ro

volumes:
  asterisk-conf:
